### DISCUSSION TITLE
Using 1Password for SSH signing

### DISCUSSION THREAD

**Discussion by davidcornu** [jj-vcs/jj#3750] [General]
In case anyone has the same question, it is indeed possible to leverage 1Password's SSH integration to sign commits with Jujutsu's recently-shipped signing support (https://developer.1password.com/docs/ssh/git-commit-signing/).

In Jujutsu's `config.toml` (`~/Library/Application Support/jj/config.toml` on macOS), set

```toml
[signing]
sign-all = true
backend = "ssh"
key = "your-public-key-here" # You can copy this out of the SSH key entry in 1Password

[signing.backends.ssh]
# This value will vary by OS and can be obtained by following this step: 
# https://developer.1password.com/docs/ssh/git-commit-signing/#step-1-configure-git-commit-signing-with-ssh
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign" 
```

Hope this helps ✌️

**Comment by JacobHayes** [comment]
It looks like [setting the `SSH_AUTH_SOCK` env var](https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client) (eg: in shell's rc file) works with the simple config too (and then you don't have to worry about OS-specific paths, at least in the jj config file):
```
[signing]
backend = "ssh"
key = "your-public-key-here"
sign-all = true
```

---

Also, using `jj --debug commit` is pretty helpful when trying to figure this out; the output will include things like:
```
2024-12-24T16:25:20.754285Z  INFO run_command:cmd_commit: jj_lib::ssh_signing: running SSH signing command command="ssh-keygen" "-Y" "sign" "-f" "<path to pubkey>" "-n" "git"
```

**Comment by jasikpark** [comment]
For Windows Powershell, I've used:

```toml
[signing]
behavior = "own"
backend = "ssh"
key = "your-public-key-here" # You can copy this out of the SSH key entry in 1Password

[signing.backends.ssh]
# This value will vary by OS and can be obtained by following this step:
# https://developer.1password.com/docs/ssh/git-commit-signing/#step-1-configure-git-commit-signing-with-ssh
program = "C:/Users/caleb/AppData/Local/Microsoft/WindowsApps/op-ssh-sign.exe"
```
