### DISCUSSION TITLE
Efforts to bring Jujutsu into Starship prompt

### DISCUSSION THREAD

**Discussion by azzamsa** [jj-vcs/jj#4208] [General]
Hi,

Currently, there are two open PRs:
- [feat(jj): add module for Jujutsu current change ID by poliorcetics · Pull Request #5814 · starship/starship](https://github.com/starship/starship/pull/5814)
- [[FR] Support Jujutsu VCS (git backed) · Issue #6076 · starship/starship](https://github.com/starship/starship/issues/6076)

We also have:
- [Starship · martinvonz/jj Wiki](https://github.com/martinvonz/jj/wiki/Starship)

@maralorn, I am not the author of either of these PRs. However, would you like to take a look and possibly give some suggestions, since you already have a working solution?

Thanks! 🥞

**Comment by NullPlane** [comment]
Oh my posh maybe would also be neat
On windows tho for cmd that'd need to be 
lua for [clink.](https://github.com/chrisant996/clink)

**Comment by amiryal** [comment]
Something that was brought up in one of the issue threads at starship/starship, which is also the case for the current wiki entry, is that snapshotting will happen on every prompt if `--ignore-working-copy` is not used. This will be surprising to anyone who doesn’t expect it, and would thus be a bad default. For colocated repos, Starship’s `git_status` module provides a best-effort alternative (good for non-merge commits that have no file conflicts).

---

Coincidentally, I just started using Starship a few hours before the OP was published! Thus far, I customised it to show three pieces of information that I care about in my (all colocated) repos, plus relying on the `git_status` module as mentioned above, plus always showing Git’s current `HEAD`:

```toml
[git_commit]
only_detached = false

[custom.jj_branch]
when = "jj workspace root --ignore-working-copy"
command = '''jj log -r "(immutable_heads()..@):: & branches()" -T 'local_branches.join("\n") ++ "\n"' --no-graph --ignore-working-copy | head -n 1'''
style = 'yellow'

[custom.jj_op]
when = "jj workspace root --ignore-working-copy"
command = 'jj op log -n 1 -T "id.short()" --no-graph --ignore-working-copy'
symbol = 'op:'
style = "bright-yellow"

[custom.jj_git_notinsync]
when = '[ -n "${jj_git_head:=$(jj log -T commit_id --no-graph --ignore-working-copy -r HEAD@git)}" ] && [ -n "${git_head:=$(git rev-parse HEAD)}" ] && [ "$git_head" != "$jj_git_head" ]'
command = 'jj log -T "commit_id.short()" --no-graph --ignore-working-copy -r HEAD@git'
symbol = 'jj:git≠'
style = 'bold red'
```

(Note that it only shows one branch, even when the line of work includes multiple ones, and gives no indication if there are more.)
