### DISCUSSION TITLE
How to run prettier against changed files using jj fix

### DISCUSSION THREAD

**Discussion by joefiorini** [jj-vcs/jj#4291] [Q&A] [answered]
I'm working in a TypeScript/React codebase that consists of json, html, TypeScript and CSS files. Prettier is a great formatter that can handle all of these filetypes. However, when using stdin/stdout it needs to be explicitly told what parser to use for formatting (ie. html, typescript, etc). I tried setting up a `fix.tool-command` that passes `--parser typescript` but obviously that breaks as soon as it tries to run against `package.json`. Has anyone found a way to use prettier with `jj fix` like this? Does jj pass the filename in any way to the tool command?

**Comment by bnjmnt4n** [comment, marked as answer]
Here's my Prettier setup:

```toml
fix.tools.prettier.command = ["npx", "prettier", "--stdin-filepath=$path"]
fix.tools.prettier.patterns = ["glob:'**/*.tsx'", "glob:'**/*.ts'", "glob:'**/*.jsx'", "glob:'**/*.js'", "glob:'**/*.css'", "glob:'**/*.html'"]
```

You can use `$path`, and Prettier should be able to infer the filetype from the pathname.
