### DISCUSSION TITLE
Delta for diffs

### DISCUSSION THREAD

**Discussion by robinst** [jj-vcs/jj#4690] [General]
I'm used to https://github.com/dandavison/delta for looking at diffs, and was wondering how to set it up with jj. I started with just setting the tool:

```toml
[ui.diff]
tool = "delta"
```

That results in this:

```
$ jj diff

Δ var/folders/jl/2lwh7cg533j2f03mnjk7vfv80000gn/T/jj-diff-plVolZ/left/docs/index.md ⟶   var/folders/jl/2lwh7cg533j2f03mnjk7vfv80000gn/T/jj-diff-plVolZ/right/docs/index.md
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

─────┐
• 1: │
─────┘
# Jujutsu—a version control system
# Jujutsu—a version control system test

## Welcome to `jj`'s documentation website!

Warning: Tool exited with exit status: 1 (run with --debug to see the exact invocation)
```

Note the very long left/right path. It can be improved like this:

```toml
[ui.diff]
tool = ["delta", "$left", "$right", "--file-transformation", "s|.*/jj-diff-[^/]*/[^/]*/||"]
```

```
$ jj diff

Δ docs/index.md ⟶   docs/index.md
────────────────────────────────────────────────────────────────────────────────

─────┐
• 1: │
─────┘
# Jujutsu—a version control system
# Jujutsu—a version control system test

## Welcome to `jj`'s documentation website!

Warning: Tool exited with exit status: 1 (run with --debug to see the exact invocation)
```

What I haven't found is how to silence the warning at the end:

```
Warning: Tool exited with exit status: 1 (run with --debug to see the exact invocation)
```

Has anyone figured out how? Any other tips?

**Comment by robinst** [comment]
Shortly after posting this, I found the [section about pagers](https://martinvonz.github.io/jj/latest/config/#processing-contents-to-be-paged) in the docs, and this makes `jj diff` work nicely:

```toml
[ui]
pager = "delta"

[ui.diff]
format = "git"
```

I'll leave this post up because I couldn't find how to configure delta before (and I searched through discussions).

One problem that's left is with the above config, `jj log -p` doesn't use the pager, but that seems to be a known issue:
- https://github.com/martinvonz/jj/issues/4142

**Comment by david-crespo** [comment]
Loving `delta` as my pager, but I was annoyed that `jj log` output would disappear on quit — I often use the log to find a change ID to plug into a subsequent command.

It turns out that by default, [`jj` uses `less -FRX`](https://jj-vcs.github.io/jj/latest/config/#pager) as its pager, and the `X` means "leave the last view as output in the terminal when you quit". But `delta`, when it calls `less` internally, must not pass `-X` because it doesn't do that.

To use jj’s default `less` command while still using delta you can do:

```toml
pager = ["delta", "--pager", "less -FRX"]
```

I don’t love this either because when I look at a diff, I don’t usually want it to stick around. I only want this behavior when I’m looking at the log, and even then, I might not want it all the time. It [turns out](https://github.com/gwsw/less/issues/36#issuecomment-913200056) you can put the following in `~/.lesskey` to make Q keep the output on quit while q does the regular quit:

```
Q toggle-option -!^Predraw-on-quit\nq
```

Then `pager = "delta"` works just fine. Note that for this to work on macOS, I had to `brew install less` to get a newer version than the super old one that comes built in.

**Comment by rwjblue** [comment]
Thanks for that @david-crespo! It got me thinking about the newish `--scope` features. I've just updated my config to only use `delta` as a pager for `jj diff` (I think this support landed in ~ 0.26). That looks like:

```toml
[[--scope]]
--when.commands = ["diff"]

[--scope.ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"
# NOTE: this is required when using `delta` as a pager
diff.format = "git"
```

With this config, `jj log` contents stay on screen properly! 🎉 

---

I was worried that this might break `jj log -p` formatting (because now `log` wouldn't be using `delta` as a pager), but apparently that doesn't work yet anyways (see https://github.com/jj-vcs/jj/issues/4142).

**Reply by david-crespo** [reply]
Nice. You might also want it for `show`.

**Reply by BoscoDomingo** [reply]
```toml
[diff]
tool = "delta"

[ui]
diff-formatter = ":git" # required by `delta`
pager=["delta", "--pager", "less -FRX"] # Keeps output from the terminal after closing the pager

# These options allow for `jj diff` and `jj show` to clear the output from the terminal after closing the pager.
[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
pager = "delta"
```

The most up-to-date version. Keeps all log output other than `jj diff` and `jj show`, using delta as the diff tool

**Reply by salty-horse** [reply]
Should this play nice with flags like `jj show --ignore-space-change`? It's being ignored for me.

**Reply by david-crespo** [reply]
That is a git diff flag but as far as I can tell it is not a jj show flag. If that’s correct, I’m surprised it doesn’t error.

**Reply by salty-horse** [reply]
But `jj diff --ignore-space-change` also doesn't work with `delta` enabled using the above configuration. Both work with `delta` disabled.

**Reply by david-crespo** [reply]
Ah, I see. And here it is defined as an arg on both diff and show. Seems like a bug! Or maybe a necessary consequence of the `:git` diff formatter.

https://github.com/search?q=repo%3Ajj-vcs%2Fjj%20ignore_space_change&type=code

**Reply by salty-horse** [reply]
My mistake. I had `diff-formatter = "delta"` instead of `":git"`.

**Comment by JacobHayes** [comment]
Has anyone been able to get [`colorMoved`](https://dandavison.github.io/delta/color-moved-support.html)[1] working well? It's generated by `git`, so guessing `ui.diff.format = "git"` would need to support it or use a different `ui.diff.tool`. Unfortunately, using `delta` for `ui.diff.tool` breaks `delta`'s color theme detection.

1: detect moved code and highlight differently than just add/delete

**Comment by ansel1** [comment]
Using @BoscoDomingo latest settings, works great.   But I was thinking if I added:

    [ui]
    conflict-marker-style = "git"

...delta would use it's [special merge conflict handling](https://dandavison.github.io/delta/merge-conflicts.html), but it doesn't seem to work.  Any idea why?

**Reply by scott2000** [reply]
Looks like they're expecting `++` at the start of the line, like `git diff` does when showing conflicts: https://github.com/dandavison/delta/blob/d5e0565cbfa47acde98d41d8777ace5d1bc4d690/src/handlers/merge_conflict.rs#L81

**Reply by shyun3** [reply]
Is there a way that `jj` can also produce these sorts of diffs on conflicts with the `:git` diff formatter?

**Comment by roteiro** [comment]
~~One issue that remains for me with using `delta` for looking at diffs (under Windows11 terminal) with the `side-by-side` option enabled is It always outputs the diff as if the terminal is 80 columns wide, even though my terminal is much wider, as described here: https://github.com/jj-vcs/jj/issues/6959.
Since [v0.34.0](https://github.com/jj-vcs/jj/releases/tag/v0.34.0) there is the `$width` variable, but I could not find a way to forward this to delta such that it uses the full terminal width. 
Anybody has a solution for that problem? If I invoke delta directly, e.g.~~
```
delta --side-by-side file1 file2
```
~~it works as expected.~~

Got it working with:
```
[ui]
diff-formatter="delta"
[merge-tools.delta]
diff-args=["--side-by-side", "$left", "$right", "--width=$width"]
```

**Comment by PicoJr** [comment]
This PR #5257 fixes the warning `Warning: Tool exited with exit status: 1 (run with --debug to see the exact invocation)`

The changelog describing the new option is here: https://jj-vcs.github.io/jj/latest/changelog/#0260-2025-02-05

I configured it using:

```toml
[ui]
diff-formatter = "delta"

[merge-tools]
delta.diff-expected-exit-codes = [0, 1]
```

**Comment by noidilin** [comment]
The current setup that works for me:

- formatter set to `delta` for syntax highlighting to work
- stop using delta as pager 
- pass computed width from jj to delta via `$width`

```toml
# allow for `jj diff` and `jj show` to clear output from terminal after pager closed
[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
# stop using delta as the pager for already-delta-formatted output
pager = ["less", "-FR"] # seems to be default (?)
# keep delta as external diff formatter to diffs real temp files/dir and keep syntax highlighting
diff-formatter = "delta"

# pass jj's computed terminal width via $width
[merge-tools.delta]
diff-args = ["--width=$width", "$left", "$right"]
```

**Comment by ansel1** [comment]
My current setup is simply:

```toml
[ui]
diff-formatter = "delta"

[merge-tools.delta]
diff-args = ["--side-by-side", "$left", "$right", "--width=$width"]
diff-expected-exit-codes = [0,1]

[aliases]
diffnav = ["diff", "--config=ui.diff-formatter=':git'", "--config=ui.pager='diffnav'"]
```

That seems to support `jj diff`, `jj show` and `jj log -p`.  Performance is fine, even for large diffs.  The `diffnav` alias lets me opt-in to diffnav for full diff browsing (a delta fork which has a file tree browser on the left).
