### DISCUSSION TITLE
Depracation warning on every command after update

### DISCUSSION THREAD

**Discussion by chahak13** [jj-vcs/jj#4742] [Q&A] [answered]
Hello! 

Thank you for working on `jj`, it's been wonderful using it. Today I updated to v0.22.0 and every command starting showing this deprecation warning 

```
Warning: In template expression
 --> 7:17
  |
7 |                 branches.join(", "),
  |                 ^------^
  |
  = branches() is deprecated; use bookmarks() instead
```

I don't have any templates defined anywhere in my configuration. Here's my `jj/config.toml`

```toml
[user]
name = "Chahak Mehta"
email = "chahak@arch.co"

[ui]
editor = "emacsclient"
default-command = ["log", "-n", "10"]
log-word-wrap = true
```

Any suggestions as to how to stop this warning or where to look for this? Since I have the jj commit in my prompt, it actually shows up on every command.

Any help would be appreciated!
