### DISCUSSION TITLE
Extra config includes by default

### DISCUSSION THREAD

**Discussion by bjeanes** [jj-vcs/jj#5653] [Q&A] [answered]
Use-case is checking in my `config.toml` generally (or more specifically in my case, generating it via Nix/home-manager) but wanting machine-local config that is not checked into dotfiles.

In Git, I can do:

```gitconfig
[include]
  path = .gitconfig.local
```

The reason for this is that the config may vary substantially between machines or may contain information (like an alternate email address) that I do not wish to be publicly documented in my (public) dotfiles.

The way I've managed this so far is:

```bash
alias jj="jj --config-file=$HOME/.jj.local.toml"
```

and 

```toml
# .jj.local.toml

[[--scope]]
--when.repositories = ["~/Code/ACME"]
[--scope.user]
email = "john@acme.corp"
```

Is this the best way? Is there an undocumented config option for extra includes or perhaps a template I can modify to change the default args to `jj` across all subcommands?
