### DISCUSSION TITLE
Is there a way to use $EDITOR as the merge-tools program?

### DISCUSSION THREAD

**Discussion by heygarrett** [jj-vcs/jj#6548] [Q&A] [answered]
What I have currently:

```toml
[merge-tools.nvimdiff]
program = "nvim"
merge-args = ["-c", "JJdiff", "-d", "$left", "$output", "$right"]
```

What I'd like to do:

```toml
[merge-tools.nvimdiff]
program = "$EDITOR"
merge-args = ["-c", "JJdiff", "-d", "$left", "$output", "$right"]
```

For context, my `EDITOR` is set to `env ENV_EDITOR=1 nvim`

**Comment by ilyagr** [comment]
I don't believe there's a built-in way.

You could make your own script like

```sh
#!/bin/sh
$EDITOR "$@"
# **Update/quick fixup:** There should *not* be quotes around $EDITOR
```

If you make it exectuable, call it `myeditor`, and put it in the PATH, replacing `nvim` with `myeditor` should work.

IIRC, Some systems (Debian derivatives, I think) have a `/usr/bin/editor` binary to call `$EDITOR` already built-in. **Update:** Though, its logic might be slightly different, and/or I may have misremembered the name. See also https://www.mankier.com/1/sensible-editor.

**Update 2:** Yeah, `/usr/bin/editor` is a symlink to something like `vim` (and you can probably point it to `nano` or something using `update-alternatives`). So, it wouldn't set the env var you wanted. `sensible-editor` would work if you have it; having your own script would be more portable.

---------

Alternatively, you could use

```toml
[merge-tools.nvimdiff]
program = "env"
merge-args = ["ENV_EDITOR=1", "nvim", "-c", "JJdiff", "-d", "$left", "$output", "$right"]
```

---------

Aside: there's also a separate issue that we might want a feature with a possible name of `jj resolve --edit` that opens the conflict in jj's default editor, even if the conflict is too complicated for a 3-way merge.

**Reply by heygarrett** [reply]
Thanks for the suggested workarounds! The `program = "env"` idea is probably what I'll go with (I'm on macOS, so I don't have `/usr/bin/editor` or `sensible-editor`), but it did get get me wondering if I could do something like this:

```toml
[merge-tools.nvimdiff]
program = "command"
merge-args = ["$EDITOR", "-c", "JJdiff", "-d", "$left", "$output", "$right"]
```

Unfortunately that doesn't appear to work:

```
~/d/s/jj/testrepo
❯ jj resolve
Resolving conflicts in: fruits.txt
/usr/bin/command: line 4: $EDITOR: command not found
Error: Failed to resolve conflicts
Caused by: Tool exited with exit status: 127 (run with --debug to see the exact invocation)
```

Would it be realistic to file a feature request to support `$EDITOR` as the merge-tools program?

**Reply by yuja** [reply, marked as answer]
As ilyagr suggested, you'll need to use `sh` to expand `$EDITOR` environment variable. Something like this might also work (see `jj util exec --help` for the trick):
```toml
program = 'sh'
merge-args = ['-c', 'exec $EDITOR "$@"', '--', ...]
```

I don't think we'll want to add support for environment variables expansion at arbitrary places. Even if we had that, `program = "$EDITOR"` wouldn't work if `$EDITOR` had command name and arguments inline.
