### DISCUSSION TITLE
How to configure `jj file show` to use `bat` for displaying file contents with syntax highlighting?

### DISCUSSION THREAD

**Discussion by bowentan** [jj-vcs/jj#6632] [Q&A] [answered]
As the title mentions, I want to use the `bat` with syntax hightlighting to display the file. Is there any way to configure it?

**Comment by jennings** [comment]
Configure it as the pager.

```toml
ui.pager = ["bat"]
```

You can use conditional configuration to make this used only for `jj file show`:

```toml
[[--scope]]
--when.commands = ["file show"]
[--scope.ui]
pager = ["bat"]
```

**Reply by ilyagr** [reply]
It would be cool if we could also pass the `--file-name` argument to `bat` with the filename. Without it, `bat` labels the file as "`STDIN`" and often (or always?) cannot decide what language's highlighting to use.

Showing "`STDIN`" uselessly can be avoided by doing `pager = ["bat", "-p"]`.

**Reply by bowentan** [reply]
As mentioned by @ilyagr the syntax highlighting cannot be enabled. Any support to feed the filename or file extension to `pager`?

**Reply by yuja** [reply, marked as answer]
Maybe you can abuse `jj diff --from='root()' --tool`?
https://jj-vcs.github.io/jj/latest/config/#generating-diffs-by-external-command

with something like
```toml
[merge-tools.bat]
diff-args = ["--color=always", "$right"]
diff-invocation-mode = "file-by-file"
```
