### DISCUSSION TITLE
How can I configure VSCode to work with jj?

### DISCUSSION THREAD

**Discussion by danybeam** [jj-vcs/jj#6856] [Q&A] [answered]
Hello everyone,
My question is basically the title. According to the docs jj should just work with vscode but I had to do some settings adjustment to get merges working properly but I still can't get the diffs to work properly. I don't know if diff-invocation-mode = "file-by-file" doesn't work or I don't understand it.

Here is my config file I know that it's getting applied because if add add junk arguments to the edit-args they get reflected when I run diffedit with debug

```TOML
[ui]
default-command = "log"
conflict-marker-style = "git"
editor = "code.cmd --wait --new-window"       # VS Code
diff-instructions = false
diff-editor = "vscode"
merge-editor = "vscode"

[merge-tools.vscode]
program = "code.cmd"
edit-args = ["--wait", "--new-window", "--diff", "$left", "$right"]
diff-args = ["--wait", "--new-window", "--diff", "$left", "$right"]
merge-args = ["--wait", "--new-window", "--merge", "$left", "$right", "$base", "$output"]
diff-invocation-mode = "file-by-file"
```

Here's a sample of what happens if I run the command
```pwsh
jj diffedit --debug
2025-06-29T01:31:06.595976Z  INFO jj_cli::cli_util: debug logging enabled
2025-06-29T01:31:06.645590Z  INFO run_command:cmd_diffedit: jj_cli::merge_tools::external: Invoking the external diff editor: cmd="code.cmd" "--wait" "--new-window" "--diff" "C:\\Users\\danybeam\\AppData\\Local\\Temp\\jj-diff-Dz3thC\\left" "C:\\Users\\danybeam\\AppData\\Local\\Temp\\jj-diff-Dz3thC\\right"
```

I've been fighting with this all day, any help is appreciated.
