### ISSUE TITLE
FR: make `$left` and `$right` environment variables expand to full file path to improve diffing integration in vscode and winmerge

### ISSUE THREAD

**Issue by wmjdgla** [jj-vcs/jj#3696]
Per https://martinvonz.github.io/jj/v0.17.1/config/, when handling diffing operations (e.g. `jj diff`, `jj split`, `jj squash -i`), `$left` and `$right` are expanded to directories. This happens even when a single file is given as argument to the command. However, vscode's diffing option (`-d`) only knows how to handle file paths; passing directory paths to it results in (produced by `jj diff -r <rev> test.txt`):
![jj-fr-vscode](https://github.com/martinvonz/jj/assets/42563269/be8d4167-faf3-4dde-8c10-7a46c7661afe)

The left and right directories are simply added to the workspace and no diff view is produced. Also, this overwrites the entire workspace despite passing `--reuse-window` to vscode. This is more of a vscode issue, but it can be avoided had we used the full file path instead. 

For winmerge, `jj diff -r <rev> test.txt` results in:
![jj-fr-winmerge](https://github.com/martinvonz/jj/assets/42563269/aab08f8b-f3e2-4baf-9ca1-6ce97ba70bb4)

Double-clicking the file entry produces the diff view, but we could have accessed it directly had we used the full file path instead.

When multiple files are changed in a commit, expanding `$left` and `$right` to directories makes sense if users don't specify which file they want to target. But if they do, then it would be great to expand to the full file path so that they can directly access the file diff.

The TOML settings I used:
```toml
# Uncomment as desired
#ui.diff.tool = "vscode"
#ui.diff-editor = "vscode"

#ui.diff.tool = "winmerge"
#ui.diff-editor = "winmerge"

merge-tools.vscode.diff-args = ["--reuse-window", "-w", "-d", "$left", "$right"]
merge-tools.vscode.edit-args = ["--reuse-window", "-w", "-d", "$left", "$right"]
merge-tools.winmerge.edit-args = ["/e", "$left", "$right"]
merge-tools.winmerge.diff-args = ["/e", "$left", "$right"]

merge-tools.vscode.program = "C:/Users/User/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd"
merge-tools.winmerge.program = "C:/Program Files/WinMerge/WinMergeU.exe"
```
