### ISSUE TITLE
file deletion ignored by `jj split` (when using the built-in diff editor)

### ISSUE THREAD

**Issue by Zoybean** [jj-vcs/jj#3702]
## Description

`jj split` and `jj squash -i` both appear to ignore selected file deletions. This appears to be limited to the default editor (could not reproduce with `--tool meld`). They are shown in the diff editor but do not end up in the chosen commit.

## Steps to Reproduce the Problem

1. `mv foo bar`
1. `jj split`
2. select all changes
3. `jj show @-`
3. `jj show @`

## Expected Behavior
the first commit contains a file addition (bar) and a file deletion (foo)
the second commit is empty

## Actual Behavior
the first commit contains a file addition (bar)
the second commit contains a file deletion (foo)

## Specifications

- Platform: Windows 10
- Version: jj 0.17.1-c34f35fffe1b8e5932ba27ac4da8ba5a97d417a5

**Comment by hroi** [comment]
I'm able to reproduce this with `:builtin`, but not when running `scm-diff-editor` as an external tool:

```toml
# config.toml
# Install scm-diff-editor binary:
# cargo install --git https://github.com/arxanas/scm-record.git --features scm-diff-editor

[ui]
# diff-editor = ":builtin"
diff-editor = "scm-diff-editor"

[merge-tools.scm-diff-editor]
program = "/path/to/scm-diff-editor"
edit-args = ["--dir-diff", "$left", "$right"]
```
