### ISSUE TITLE
Bug: Can't use quotes in `ui.editor`/`$EDITOR`

### ISSUE THREAD

**Issue by Cretezy** [jj-vcs/jj#3753]
## Description

Using one of the following does not apply arguments correctly:

```toml
ui.editor = "nvim --cmd 'let g:flatten_wait=1'"
# or
ui.editor = "code '-w'"
```
```shell
EDITOR="nvim --cmd 'let g:flatten_wait=1'"
# or
JJ_EDITOR="code '-w'" jj describe
```

Although this works:
```toml
ui.editor = ["nvim", "--cmd", "let g:flatten_wait=1"]
# or
ui.editor = ["code", "-w"]
```

## Steps to Reproduce the Problem

1. Set `ui.editor` or `$EDITOR` to have quotes
1. Run `jj describe`

E.g. `JJ_EDITOR="code '-w'" jj describe`

## Expected Behavior

Quoted arguments should be used correctly.

## Actual Behavior

Quoted arguments are ignored (at least for the `code '-w'` example above, the `nvim` throws an error but that's likely because `let` isn't quoted properly).

## Specifications

- Platform: Arch Linux, same behavior on macOS IIRC
- Version: 0.17.1/`main`
