### ISSUE TITLE
FR: Add support for italic formatting

### ISSUE THREAD

**Issue by zx8** [jj-vcs/jj#5089]
**Describe the solution you'd like**

Currently, we can do e.g.

```toml
[colors]
commit_id = { fg = "green", bg = "#ff1525", bold = true, underline = true }
```

Would it be possible to add support for `italic = true` as well?
