### ISSUE TITLE
FR: Conditional config should accept traditional Windows path format

### ISSUE THREAD

**Issue by jennings** [jj-vcs/jj#5143]
**Is your feature request related to a problem? Please describe.**
The following conditional config does not work on Windows

```toml
[[--scope]]
--when.repositories = ["C:/src/github.com"]
# also doesn't work:
#--when.repositories = ["C:\\src\\github.com"]

[--scope.user]
email = "stephen@example.com"
```

Instead, the `--when` must use [DOS device paths](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths) to work properly:

```toml
--when.repositories = ["\\\\?\\C:\\src\\github.com"]
```

**Describe the solution you'd like**
Traditional DOS paths should be recognized (`"C:/src/github.com"` or `"C:\\src\\github.com"`).
