### ISSUE TITLE
Conditional config doesn't apply when initializing or cloning a repository

### ISSUE THREAD

**Issue by jennings** [jj-vcs/jj#5144]
## Description

When initializing or cloning a new repository, conditional config is not considered when creating the first empty commit.

## Steps to Reproduce the Problem

1. Add the following conditional config (Windows, but probably not relevant to this issue):
   ```toml
   [user]
   name = "Stephen"
   [[--scope]]
   --when.repositories = ["\\\\?\\C:\\src\\github.com"]
   [--scope.user]
   email = "stephen@example.com"
   ```
2. Execute: `jj git clone git@github.com:jj-vcs/jj C:\src\github.com\jj`

## Expected Behavior

The working copy commit created by jj should have the email `stephen@example.com`.

## Actual Behavior

The working copy commit has no email address set.

## Specifications

- Platform: Windows
- Version: jj 0.24.0-f5d450d7c3a8f8a49e30aef0fd18d8295ffc8cb6
