### ISSUE TITLE
Some config doesn't work when loaded via --config-file

### ISSUE THREAD

**Issue by teatwig** [jj-vcs/jj#5282]
## Description

It seems like some config such as aliases and ui.default-command don't work if they're loaded via `--config-file`, but do work if they're specified in the regular config file.

Other options like
```toml
[colors]
working_copy = { bold = false }
```
work without issues.

## Steps to Reproduce the Problem

1. Create a new file `jjconfig2.toml` with the following contents:
```toml
[aliases]
l = ["log"]
```
1. Run `jj --config-file=jjconfig2.toml l`

## Expected Behavior

The log is displayed.

## Actual Behavior

```
error: unrecognized subcommand 'l'
```

## Specifications

- Platform: Linux
- Version: 0.25.0
