### ISSUE TITLE
FR: Language detection in filesets for `jj fix`

### ISSUE THREAD

**Issue by saulrh** [jj-vcs/jj#5343]
**Is your feature request related to a problem? Please describe.**

1. Have a directory of mixed shebang scripts, e.g. `script/a-python-script` and `script/a-bash-script`
2. Create a new script
3. Forget to update the fifty-line `patterns` expressions in `.jj/config.toml`
4. Invoke `jj fix`
5. New script is not fixed

Or:

1. Have a directory of mixed shebang scripts, e.g. `script/a-python-script` and `script/a-bash-script`
2. Notice that `script/way-too-big` is way too big to still be in bash and rewrite it in python
3. Update `.jj/config.toml` to format `script/way-too-big` with `ruff` instead of `shfmt`
4. Invoke `jj fix`
5. Previous revision gets rewritten having run `ruff` on the bash version of `script/way-too-big`

**Describe alternatives you've considered**

1. File types as a first-class citizen

Surely there's a library out there's that ingested the whole "let's just solve the file formats problem" wiki and defined an ontology. Grab that, then let people write things like, idk, `filetype:'python - executable'`.

Advantages:
- Gotta love formal ontologies
Disadvantages:
- You could work on it for the next hundred years and make no appreciable progress

2. Free-form file type command

Configuration holds a command that maps files to filetype strings, then let people match against a file's filetype string. For example:

```toml
[filetypes]
command = "file --mime-type --brief"

[fix.tools.ruff]
patterns = ["filetype:'text/x-script.python'"]

[fix.tools.shfmt]
patterns = ["filetype:'text/x-shellscript'"]
```

Advantages: 
- Conceptually simple
Disadvantages:
- Each file can only be a single type
- Choosing a sufficiently portable default implementation might be tricky, e.g. I use a simple `file` invocation up there but that "implementation" has tons of room for subtle bugs: `file --brief --mime-type ~/.emacs.d/init.el` on my machine is `inode/symlink`, for example
- No smooth path from "trivial inline invocation of `file`" to "that, but with one or two tweaks" - In my head I'm already designing the wrapper script I'd have to put around `file`

3. Pluggable predicate system

A filetype consists of a command that, when run on a program, indicates whether it's part of the filetype.

```toml
[filetypes]
python = ["scripts/is-python.sh", "--file=$path", "-"]
shell = '[ "$(file --brief --mime-type)" = "text/x-shellscript" ]'
shebang = "head -n 1 | grep -E '^#!'"

[fix.tools.ruff]
patterns = ["filetype:python" & "filetype:shebang"]

[fix.tools.shfmt]
patterns = ["filetype:python" & "filetype:shebang"]
```

Advantages:
- Flexible
- Conceptually simple
- Single file can match multiple filetypes
Disadvantages:
- Performance could be an issue
- Huge directory full of bespoke shell scripts
- Suggests specially-blessed filetype predicates implemented in `jj` core in rust, which is prooooobably a bad idea

4. Pluggable listings

A filetype is the set of files printed by the invocation of some program.

```toml
[filetypes]
shell = ["shfmt", "--find", "."]
```

Advantages:
- Flexible?
- Minimizes process invocation overhead
Disadvantages:
- Requires whole repository to be materialized at every tested revision :no_entry_sign:
