### ISSUE TITLE
BUG: `jj git fetch` creates an empty change with `[[--scope]]` settings being ignored

### ISSUE THREAD

**Issue by teenjuna** [jj-vcs/jj#5603]
## Description

I use different identity settings for personal stuff and work, e.g. in my config file I have something like this:
```toml
[user]
name = "Alex"
email = "alex@personal.com"

[[--scope]]
--when.repositories = ["~/Git/git.work.com"]
[--scope.user]
name = "Alex"
email = "alex@work.com"
```

When I freshly clone a work-related repo inside `~/Git/git.work.com` and `jj log` inside it, I see this:
```
@  rtwzklzt alex@personal.com 2025-02-06 15:16:51 a0cd8d2a
│  (empty) (no description set)
◆  vqqvouzl alex@work.com 2025-02-06 15:09:51 main 66eca746
│  (empty) Merge branch 'XXX' into 'main'
```

Note that there is an automatically created empty change with my _personal_ email. However, when I create a new change using `jj new -m "test"` and then do `jj log`, I see this:
```
@  lkpwoqkl alex@work.com 2025-02-06 15:17:10 77ceb84b
│  (empty) test
○  rtwzklzt alex@personal.com 2025-02-06 15:16:51 a0cd8d2a
│  (empty) (no description set)
◆  vqqvouzl alex@work.com 2025-02-06 15:09:51 main 66eca746
│  (empty) Merge branch 'XXX' into 'main'
```

Note that this change was created with my _work_ email as intended.

## Expected Behavior

Automatically created empty change should respect `[[--scope]]` settings.

## Actual Behavior

Automatically created empty change ignores `[[--scope]]` settings.

## Specifications

- Platform: MacOS
- Version: 0.25.0
