### ISSUE TITLE
[jsonschema] <key> is valid under more than one of the schemas listed in the 'oneOf' keyword

### ISSUE THREAD

**Issue by zx8** [jj-vcs/jj#5607]
Testing out the new JSON Schema and came across an issue.

Pretty simple repro:

```toml
"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[colors]
author = "blue"
```

Error:

```
"author" is valid under more than one of the schemas listed in the 'oneOf' keyword
```
