### ISSUE TITLE
config schema raises an error when using an array for ui.editor

### ISSUE THREAD

**Issue by heygarrett** [jj-vcs/jj#5617]
## Description

As a workaround to #3753 I've configured ui.editor using an array of strings:

```toml
[ui]
editor = ["nvim", "--cmd", "let g:launched_by_shell=1"]
```

But after adding the schema to the top of the config file:

```toml
"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"
```

[Taplo](https://github.com/tamasfe/taplo) raises an error on the `editor` property:
> Even Better TOML: ["nvim","--cmd","let g:launched_by_shell=1"] is not of type "string"

## Specifications

- Platform: macOS 15.3
- Version: jj 0.26.0

**Comment by dnaka91** [comment]
Same here. Also, similar issue with the `ui.diff.tool` setting (which I see as the same issue because both settings are described in the docs to either take a string or array):
```toml
[ui.diff]
tool = ["difft", "--color=always", "$left", "$right"]
```
