### ISSUE TITLE
FR: Add remote URL pattern option for `--when` conditions under `[--scope]`'d config

### ISSUE THREAD

**Issue by vergenzt** [jj-vcs/jj#6028]
**Is your feature request related to a problem? Please describe.**

I currently have some git config that looks like:

```ini
# override email and signingkey if remote matches `{{ .work.github_org }}`
[includeIf "hasconfig:remote.*.url:git@github.com:{{ .work.github_org }}/**"]
    path = work-org.ini
```

where `work-org.ini` contains:

```ini
[user]
    email = {{ .work.email | quote }}
    signingkey = {{ .work.ssh_pubkey | quote }}
```

This uses git's [`includeIf.<condition>.path` config option where `<condition>` is like `hasconfig:remote.*.url:`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-codehasconfigremoteurlcode).

**Describe the solution you'd like**

I'd like to be able to conditionally set email and signing key config values based on a similar pattern on (any) remote URL for `jj`.

E.g.

```toml
[--scope]
--when.remote_url = "git@github.com:{{ .work.github_org }}/**"

user.name = "..."
user.email = "..."
signing.key = "..."
```

**Describe alternatives you've considered**
🤷 

**Additional context**
Not a huge blocker. I'm just gonna use env vars for now.

**Comment by bryceberger** [comment]
Unclear how this works with multiple remotes, potentially with completely different urls, i.e.

```toml
[[--scope]]
--when.remote_url = "glob:git@github.com:work/*"
user.email = "..."

[[--scope]]
--when.remote_url = "glob:git@sr.ht:*"
user.email = "..."
```

Could potentially be cleared by requiring the remote name as well as url? That still has the confusion of which one takes priority, but could make it more clear

```toml
[[--scope]]
--when.remote = { name = "origin", url = "glob:git@github.com/work/*" }
# ...
```

**Comment by vergenzt** [comment]
In git it works as follows:

> _The first time this [condition] is seen, the rest of the config files will be scanned for remote URLs (without applying any values). If there exists at least one remote URL that matches this pattern, the include condition is met._

I.e. _any_ remote matching the url triggers a match.

I like that approach.

**Comment by calebdw** [comment]
Why don't you just place all your work repos in a common `work/` directory and specify that?

```toml
[[--scope]]
--when.repositories = ["~/work"]
```
