### ISSUE TITLE
FR: Option for squash where you opt into each edit instead of opting out

### ISSUE THREAD

**Issue by whatisaphone** [jj-vcs/jj#6218]
**Is your feature request related to a problem? Please describe.**

In git, I liked to use the process of staging as code review/cleanup. I would stage a hunk, edit a bit, stage some more, edit, stage the rest and finally commit.

In jj I found a close analogue of this: `jj new -B@ --no-edit`, `jj squash -i`, edit a bit, `jj squash -i`, edit some more, and finally `jj desc @-`. The problem is `jj squash` defaults to including all changes, so it adds friction to a review workflow. I'll start out with 100 changes, `jj squash -i` and unapprove 99 changes, edit a bit, `jj squash -i` and unapprove 98 changes, edit more, `jj squash -i` and unapprove 97 changes, and so on.

**Describe the solution you'd like**

I'd like an option for jj squash that defaults to moving no edits, and lets the user opt in to edits one by one. With the option, JJ-INSTRUCTIONS might look something like this:

```
The left side of the diff shows the contents of the commit you're
moving changes from. The right side initially shows the contents of the
commit you're moving changes to.

Adjust the right side until the diff shows the changes you want to move
to the destination. If you don't make any changes, then the operation
will be aborted.
```

**Describe alternatives you've considered**

I read the docs and couldn't find anything close to this, but I'm open to anything I missed!

**Comment by yuja** [comment]
Just fyi, the builtin diff editor doesn't select anything by default. That's inconsistent, but might be useful.

Related issue: https://github.com/jj-vcs/jj/issues/5390

**Comment by whatisaphone** [comment]
Yeah, the builtin editor works "right" to me and the external ones don't, but I just can't give up my gui tooling haha.

I got annoyed enough to write a fix in userland. Been using it smoothly for a while. I'll leave it here in case it helps anyone.

`~/.local/bin/jj-swap`:

```sh
#!/usr/bin/env bash

set -eu

i=1
while [[ ${!i} != --swap ]]; do
    ((++i))
done

set -- "${@:1:i-1}" "${@:i+1}"
left=${*:i:1}
right=${*:i+1:1}

rm -- "${right}/JJ-INSTRUCTIONS"
chmod -R +w -- "${left}"
chmod -R -w -- "${right}"

aside=$(mktemp -u)
mv -- "${left}" "${aside}"
mv -- "${right}" "${left}"
mv -- "${aside}" "${right}"

"$@"

chmod -R +w -- "${left}" # so jj is able to delete it
```

`~/.config/jj/config.toml`:

```toml
[merge-tools.bcompare-swap]
program = "jj-swap"
# fill in your own tool here
edit-args = ["bcompare", "--swap", "$left", "$right", "-expandall"]

[aliases]
restoretool = ["restore", "--tool=bcompare-swap"]
splittool = ["split", "--tool=bcompare-swap"]
squashtool = ["squash", "--tool=bcompare-swap"]
```

Sadly it's not a seamless solution. You can't just set it as the default tool, because swapping doesn't make sense for all commands (e.g. diffedit, show, etc), and  I didn't see a way to configure the default tool per command. But the aliases are working great for me.

**Comment by cenviity** [comment]
> and I didn't see a way to configure the default tool per command

Maybe with [conditional variables](https://jj-vcs.github.io/jj/latest/config/#conditional-variables)?

**Comment by whatisaphone** [comment]
> Maybe with [conditional variables](https://jj-vcs.github.io/jj/latest/config/#conditional-variables)?

Worked perfect, thanks for the tip!

```toml
[ui]
diff-editor = "bcompare"

[[--scope]]
--when.commands = ["restore", "split", "squash"]
[--scope.ui]
diff-editor = "bcompare-swap"
```
