### ISSUE TITLE
`--when.repositories` not working if defined in extra config file

### ISSUE THREAD

**Issue by gaerfield** [jj-vcs/jj#6608]
## Steps to Reproduce the Problem

1. read go to https://jj-vcs.github.io/jj/latest/config/#using-multiple-files
1. create file `$XDG_CONFIG_HOME/jj/conf.d/test.toml`
1. paste content:
```toml
--when.repositories = ["~/the/work/repo"]

[user]
name = "blabla"
email = "blabla@workplace.com"
```
1. create directory "mkdir -p ~/the/work/repo" and cd into it "cd ~/the/work/repo"
1. get configured name "jj config g user.name"

## Expected Behavior

"blabla" is echoed

## Actual Behavior
 
whatever default is configured is echoed

## Specifications

- Platform: `Linux 6.12.28 #1-NixOS SMP PREEMPT_DYNAMIC Fri May  9 07:50:53 UTC 2025 x86_64 GNU/Linux`
- Version: 0.29.0

**Comment by gaerfield** [comment]
If I comment `--when.repositories`, the name `blabla` is echoed in every directory. Meaning the configuration file is picked and interpreted as expected.

**Comment by bnjmnt4n** [comment]
I suspect you might need to actually create a repository at that path for the command to work.

**Comment by gaerfield** [comment]
@bnjmnt4n 

* I wouldn't expect this, because jj works as a command regardless of being in a git-repo or not (although it reports in most cases an error that there is no repo present)
* `config g user.name` still reports an username, the default one, although not being in a repository{{{
* the documentation states:

> List of paths to match the repository path prefix.

If the prefix matches, a different username should be used.

I haven't tested, if the scoped config within the main config would work: `[[--scope]]`. That's maybe something worth trying.

**Comment by gaerfield** [comment]
Ok, even setting it in the config file doesn't work:
```toml
[user]
email = "default@private.tld"
name = "default"

[[--scope]]
--when.repositories = ["~/the/work/repo"]
[--scope.user]
email = "blablalba@work.tld"
name = "blablabla"
```

btw.: the why the prefixed dashes at `--scope` and `--when`. It is a valid bare toml key, but honestly it looks weird and seems not to have any semantics. Without them it looks cleaner to me:
```toml
[user]
email = "default@private.tld"
name = "default"

[[scope]]
[scope.when]
repositories = ["~/the/work/repo"]
[scope.user]
email = "blablalba@work.tld"
name = "blablabla"
```
