### ISSUE TITLE
FR: Support calling aliases with spaces without requiring quotes (or subcommand aliases)

### ISSUE THREAD

**Issue by icorbrey** [jj-vcs/jj#6611]
**Is your feature request related to a problem? Please describe.**

I want to wrap `git-tfs` to allow using Jujutsu on TFVC repos, and ideally I want them behind a `jj tfvc ____` command. Defining an alias with a space is supported technically, but it's only callable by wrapping the alias name in spaces, like so:

![Image](https://github.com/user-attachments/assets/005ac2c9-d741-4d80-a7db-293e07451f4e)

**Describe the solution you'd like**

I'd like to be able to call these aliases without having to wrap them in quotes.

**Describe alternatives you've considered**

I've considered either sucking it up and calling my aliases `tfvc-____` instead or trying to write a proper backend for TFVC, but I'd prefer to do neither.

**Comment by icorbrey** [comment]
For now I'm working around this by utilizing subcommand functions in Nushell. It's working decently nicely

**Comment by tjjfvi** [comment]
My workaround: more aliases!
```toml
aliases.foo = ["util", "exec", "--", "bash", "-c", 'jj "foo $0" "$@"']
aliases."foo bar" = ["..."]
aliases."foo baz" = ["..."]
```

![Image](https://github.com/user-attachments/assets/bfef9b21-9b93-4671-b5d1-4739a7567879)

```toml
aliases.subcommand = ["util", "exec", "--", "bash", "-c", 'jj "$0 $1" "${@:2}"']
aliases.foo = ["subcommand", "foo"]
aliases."foo bar" = ["..."]
aliases."foo baz" = ["..."]
```
